pipeline {
    agent { label 'agent1' }

    environment {
        PROJECT_NAME = 'MinimalWebApp'
        DOCKER_IMAGE = 'minimal-webapp'
        DOTNET_CLI_HOME = "${env.WORKSPACE}/.dotnet"
        DOCKER_CONFIG="/home/jenkins/.docker"
        PATH = "${env.WORKSPACE}/.dotnet/tools:${env.PATH}"
        DOTNET_CLI_TELEMETRY_OPTOUT = 1
    }

    stages {
        stage('Setup') {
            steps {
                echo "Setup..."
                sh "uname -a"
                sh "dotnet --version"
                sh "id"
                sh "ls -lart /home/jenkins/template-run/" //ls: cannot access '/root/template-run/': Permission denied
                sh "dotnet new tool-manifest --force"
                sh "dotnet tool restore"
                sh "dotnet cake --info"
            }
        }

        stage('Restore & Build') {
            steps {
                echo "Restoring and building .NET project..."
                dir("MinimalWebApp1") {
                    sh "pwd"
                    sh "ls -lart"
                    sh "dotnet restore ${PROJECT_NAME}.csproj"
                    sh "dotnet build ${PROJECT_NAME}.csproj --configuration Release"
                }
            }
        }

        stage('Run Tests (optional)') {
            steps {
                echo "No tests defined. Skipping test stage."
                // sh "dotnet test ${PROJECT_NAME}"  # uncomment if tests exist
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("MinimalWebApp1") {
                    echo "Building Docker image..."
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }
    }

    post {
        success {
            echo "✅ Build and Docker image completed successfully."
        }
        failure {
            echo "❌ Build failed."
        }
    }
}
