template: service-foundation-app-pr:250311165857
config:
  pipelineName: "kb-sf-helloworld"
  build:
    cakeScript: MinimalWebApp2/build.cake
    dockerImageBuild:
    - image: tipu/foo-webapi
      buildargs: []
      dockerfile: MinimalWebApp2/Dockerfile
      context: MinimalWebApp2/
    ecrImagePush:
    - tipu/foo-webapi
